### ISSUE TITLE
Use without request?

### ISSUE THREAD

**Issue by bradparks** [yannickcr/node-chromelogger#1]
Do we need to use a request object to log to the console?

There are times when I'm in a different context, and would like to log to the chrome console _without_ request....

Thanks!

**Comment by yannickcr** [comment]
Sadly we return the logs in the HTTP headers so we need to have access to a request response.

The only solution I can see is to make the request response available in your context or to use another logging method.

**Comment by bradparks** [comment]
ok... cool! thanks for the info and for looking into it!

**Comment by MadLittleMods** [comment]
I know this is an old issue and I found this project very intriguing but I was disappointed when I realized you need a response object to piggyback on. This factor makes this almost unusable if you aren't using Node as a web server.

It would be really cool if Node connected via sockets to the extension so that the code footprint for logging could be a simple `chromelogger.log(...)`. Maybe it has to be the way it is using the ChromeLogger extension but I think this could be less cumbersome.
